### ISSUE TITLE
NPE when installing

### ISSUE THREAD

**Issue by joseph-tobin** [cesarsotovalero/time-series-classification#1]
Hi,

I'm getting an NPE when trying to install this package. I am installing via the 'unoffical package' option in package manager using the rar file provided.
Attempted to install in versions 3.7.12 and 3.8.4
This is occuring on both Windows 10 and Ubuntu 18.04

`java.lang.NullPointerException
	at weka.core.WekaPackageLibIsolatingClassLoader.checkForNativeLibs(WekaPackageLibIsolatingClassLoader.java:220)
	at weka.core.WekaPackageLibIsolatingClassLoader.init(WekaPackageLibIsolatingClassLoader.java:145)
	at weka.core.WekaPackageLibIsolatingClassLoader.<init>(WekaPackageLibIsolatingClassLoader.java:126)
	at weka.core.WekaPackageClassLoaderManager.addPackageToClassLoader(WekaPackageClassLoaderManager.java:369)
	at weka.core.WekaPackageManager.initializeAndLoadUnofficialPackage(WekaPackageManager.java:2372)
	at weka.core.WekaPackageManager.installPackageFromArchive(WekaPackageManager.java:2359)
	at weka.gui.PackageManager$UnofficialInstallTask.doInBackground(PackageManager.java:780)
	at weka.gui.PackageManager$UnofficialInstallTask.doInBackground(PackageManager.java:724)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
`

Thanks

**Comment by cesarsotovalero** [comment]
I installed and tested the package in Ubuntu 19.04, Weka 3.8.4
Please follow the [Installation](https://github.com/cesarsotovalero/timeSeriesClassification/wiki/Installation) guide and [Usage](https://github.com/cesarsotovalero/timeSeriesClassification/wiki/Usage) example as described in the Wiki.
If the Exception persists, describe here what you have done step by step.

**Comment by joseph-tobin** [comment]
Thanks Cesar. I followed the wiki instructions and it worked.
